### ISSUE TITLE
Endereço não encontrado

### ISSUE THREAD

**Issue by deblynprado** [emersonsoares/AddressAPI#8]
Olá Emerson!

Parabéns pela API, ela é de grande ajuda!
Mas não sei se o correio mudou alguma coisa, pois ela está retornando **Endereço não encontrado** para qualquer CEP. Inclusive o que está como demo no site.

Reparei que desde domingo pela manhã já não estava retornando resultado, agora entrei direto no site, fiz o teste por lá e realmente só retorna essa mensagem.

Usei para teste os CEPs 04578-000 e 09920-000

**Comment by lguima** [comment]
> Opa @deblynprado, como a api pega os dados direto do site dos correios, provavelmente isso ocorreu devido ao site dos correios ter ficado fora do ar. Obrigado pelo report, vou abrir uma Issue para desenvolvimento de um tratamento onde caso o site dos correios esteja fora do ar a api dê uma resposta mais correta.

Foi feita essa tratativa @emersonsoares? Pois estou com o mesmo problema relatado na issue, nenhum CEP encontrado, inclusive o de exemplo.
